variables:
  AWS_DEFAULT_REGION: us-east-1
  DEV_BUCKET_NAME: docs.dev.summit.cloud.vt.edu
  DEV_DISTRIBUTION_ID: E2F2R1ABBHEMHR
  PPRD_BUCKET_NAME: docs.pprd.summit.cloud.vt.edu
  PPRD_DISTRIBUTION_ID: E36DWFQ4C0HMPI
  PROD_BUCKET_NAME: docs.summit.cloud.vt.edu
  PROD_DISTRIBUTION_ID: EZ38I4CILIUX2
  
stages:
  - build
  - dev-deploy
  - pprd-deploy
  - prod-deploy

build:
  image: docker
  script:
    - docker image build -t summit/docs:$CI_COMMIT_SHA
    
dev-deploy:
  stage: dev-deploy
  environment: dev
  only:
    - master
  image: summit/docs:$CI_COMMIT_SHA
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export S3_BUCKET_NAME=$DEV_BUCKET_NAME
    - export CLOUDFRONT_DISTRIBUTION_ID=$DEV_DISTRIBUTION_ID
    - node ./deploy.js

pprd-deploy:
  stage: pprd-deploy
  environment: pprd
  when: manual
  only:
    - master
  image: summit/docs:$CI_COMMIT_SHA
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export S3_BUCKET_NAME=$PPRD_BUCKET_NAME
    - export CLOUDFRONT_DISTRIBUTION_ID=$PPRD_DISTRIBUTION_ID
    - node ./deploy.js

prod-deploy:
  stage: prod-deploy
  environment: production
  when: manual
  only:
    - master
  image: summit/docs:$CI_COMMIT_SHA
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export S3_BUCKET_NAME=$PROD_BUCKET_NAME
    - export CLOUDFRONT_DISTRIBUTION_ID=$PROD_DISTRIBUTION_ID
    - node ./deploy.js
