variables:
  AWS_DEFAULT_REGION: us-east-1
  DEV_BUCKET_NAME: docs.dev.summit.cloud.vt.edu
  DEV_DISTRIBUTION_ID: E2F2R1ABBHEMHR
  PPRD_BUCKET_NAME: docs.pprd.summit.cloud.vt.edu
  PPRD_DISTRIBUTION_ID: E36DWFQ4C0HMPI
  PROD_BUCKET_NAME: docs.summit.cloud.vt.edu
  PROD_DISTRIBUTION_ID: EZ38I4CILIUX2
  
stages:
  - build
  - dev-deploy
  - pprd-deploy
  - prod-deploy

before_script:
  - aws configure set preview.cloudfront true

build:
  before_script:
    - /bin/true  # override global before_script
  stage: build
  image: moird/mkdocs
  script:
    - mkdocs build --clean
    - rm -rf site/images-notconverted
  artifacts:
    name: site-build
    expire_in: 1 week
    paths:
      - site/
    
dev-deploy:
  stage: dev-deploy
  environment: dev
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - aws s3 sync --delete site/ s3://${DEV_BUCKET_NAME}/
    - aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --paths "/releaseNotes/*"

pprd-deploy:
  stage: pprd-deploy
  environment: pprd
  when: manual
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - aws s3 sync --delete site/ s3://${PPRD_BUCKET_NAME}/
    - aws cloudfront create-invalidation --distribution-id ${PPRD_DISTRIBUTION_ID} --paths "/releaseNotes/*"

prod-deploy:
  stage: prod-deploy
  environment: production
  when: manual
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - aws s3 sync --delete site/ s3://${PROD_BUCKET_NAME}/
    - aws cloudfront create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --paths "/releaseNotes/*"
