stages:
  - build
  - push-image
  - update-stack

variables:
  DOCKER_IMAGE_NAME: $REGISTRY_HOST/summit/denali-docs:$CI_COMMIT_SHA
  AWS_DOCKER_IMAGE_NAME: $AWS_REGISTRY_HOST/qa/docs:$CI_COMMIT_SHA

build:
  stage: build
  image: docker
  script:
    - docker image build -t summit/docs:$CI_COMMIT_SHA .
   
push-image:
  stage: push-image
  image: docker
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_HOST
    - docker tag summit/docs:$CI_COMMIT_SHA $DOCKER_IMAGE_NAME
    - docker push $DOCKER_IMAGE_NAME

push-image-aws:
  stage: push-image
  image: docker
  script:
    - apk add --no-cache python py-pip
    - pip install awscli
    - export AWS_ACCESS_KEY_ID=$QA_REGISTRY_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$QA_REGISTRY_SECRET_ACCESS_KEY
    - $(aws ecr get-login --no-include-email)
    - docker tag summit/docs:$CI_COMMIT_SHA $AWS_DOCKER_IMAGE_NAME
    - docker push $AWS_DOCKER_IMAGE_NAME

update-stack:
  stage: update-stack
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG-docs.summit-qa.research.vt.edu
    on_stop: remove-from-stack
  image: node
  script:
    - curl -X POST -F token=$ENV_REPO_TRIGGER_TOKEN -F ref=update-stack -F "variables[ACTION]=deploy" -F "variables[ENV_BRANCH]=${CI_COMMIT_REF_NAME}" -F "variables[UPDATED_SERVICE]=docs" -F "variables[NEW_IMAGE]=$DOCKER_IMAGE_NAME" https://code.vt.edu/api/v4/projects/2182/trigger/pipeline

remove-from-stack:
  stage: update-stack
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  image: node
  script:
    - curl -X POST -F token=$ENV_REPO_TRIGGER_TOKEN -F ref=update-stack -F "variables[ACTION]=undeploy" -F "variables[ENV_BRANCH]=${CI_COMMIT_REF_NAME}" -F "variables[UPDATED_SERVICE]=docs" -F "variables[NEW_IMAGE]=$DOCKER_IMAGE_NAME" https://code.vt.edu/api/v4/projects/2182/trigger/pipeline 
