variables:
  AWS_DEFAULT_REGION=us-east-1
  
stages:
  - build
  - dev-deploy
  - pprd-deploy
  - prod-deploy
  - sandbox-deploy


build:
  stage: build
  image: moird/mkdocs
  script:
    - mkdocs build --clean
    - rm -rf site/images-notconverted
  artifacts:
    name: site-build
    expire_in: 1 week
    paths:
      - site/
    

dev-deploy:
  stage: dev-deploy
  environment: dev
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - aws s3 sync --delete site/ s3://${DEV_BUCKET_NAME}/
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id $DEV_DISTRIBUTION_ID --paths "/releaseNotes/*"

pprd-deploy:
  stage: pprd-deploy
  environment: pprd
  when: manual
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws s3 sync --delete site/ s3://${PPRD_BUCKET_NAME}/

prod-deploy:
  stage: prod-deploy
  environment: production
  when: manual
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws s3 sync --delete site/ s3://${PROD_BUCKET_NAME}/
  
sbox-deploy:
  stage: sandbox-deploy
  environment: sandbox
  # Won't need this once GitLab issue #26360 is resolved (https://gitlab.com/gitlab-org/gitlab-ce/issues/26360)
  when: manual
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws s3 sync --delete site/ s3://${SANDBOX_BUCKET_NAME}/
