stages:
  - build
  - push-image
  - update-stack

variables:
  DOCKER_IMAGE_NAME: $REGISTRY_HOST/summit/denali-ui:$CI_COMMIT_SHA

build:
  stage: build
  image: docker
  script:
    - docker image build -t summit/docs:$CI_COMMIT_SHA .
   
push-image:
  stage: push-image
  image: docker
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_HOST
    - docker tag summit/docs:$CI_COMMIT_SHA $DOCKER_IMAGE_NAME
    - docker push $DOCKER_IMAGE_NAME

update-stack:
  stage: update-stack
  except:
    - tags
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG-docs.summit-qa.research.vt.edu
    on_stop: remove-from-stack
  image: node
  script:
    - curl -X POST -F token=$ENV_REPO_TRIGGER_TOKEN -F ref=update-stack -F "variables[ACTION]=deploy" -F "variables[ENV_BRANCH]=${CI_COMMIT_REF_NAME}" -F "variables[UPDATED_SERVICE]=docs" -F "variables[NEW_IMAGE]=$DOCKER_IMAGE_NAME" https://code.vt.edu/api/v4/projects/2182/trigger/pipeline

remove-from-stack:
  stage: update-stack
  except:
    - tags
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  image: node
  script:
    - curl -X POST -F token=$ENV_REPO_TRIGGER_TOKEN -F ref=update-stack -F "variables[ACTION]=undeploy" -F "variables[ENV_BRANCH]=${CI_COMMIT_REF_NAME}" -F "variables[UPDATED_SERVICE]=docs" -F "variables[NEW_IMAGE]=$DOCKER_IMAGE_NAME" https://code.vt.edu/api/v4/projects/2182/trigger/pipeline 
