stages:
  - build
  - dev-deploy
  - pprd-deploy
  - prod-deploy


build:
  stage: build
  image: moird/mkdocs
  script:
    - mkdocs build --clean
    - rm -rf site/images-notconverted
  artifacts:
    name: site-build
    expire_in: 1 week
    paths:
      - site/
    

dev-deploy:
  stage: dev-deploy
  environment: dev
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws --region=us-east-1 s3 sync --delete site/ s3://${DEV_BUCKET_NAME}/

pprd-deploy:
  stage: pprd-deploy
  environment: pprd
  when: manual
  only:
    - master
  image: mikesir87/aws-cli
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws --region=us-east-1 s3 sync --delete site/ s3://${PPRD_BUCKET_NAME}/
  