site_name: Summit Docs
theme_dir: 'custom_theme'

pages:
- Home: 'index.md'
- Navigation:
  - 'General': 'Navigation/general.md'
  - 'Notifications': 'Navigation/notifications.md'
  - 'Proposal Navigation': 'Navigation/proposal.md'
- Data:
  - 'Initiator': 'data/Proposal Initiator.md'
  - 'Editor (Sections)': 'data/Proposal Editor.md'
  - 'Budget Development': 'data/Budget Development.md'
- Approvals:
  - 'Proposal Routing': 'Approvals/Proposal Routing.md'
- Tools:
  - 'Actions': 'Tools/Actions.md'
  - 'Comments': 'Tools/Comments.md'
  - 'Files': 'Tools/Files.md'
  - 'Requirements': 'Tools/Requirements.md'
- Management:
  - 'Sponsors': 'Management/Sponsor Editor.md'
  - 'Organizations': 'Management/Org Editor.md'
  - 'Assignees': 'Management/Assignees.md'
- Reporting:
  - 'Data Exports': 'Reporting/Data Exports.md'
