site_name: Summit User Guide
theme_dir: 'custom_theme'
dev_addr: 0.0.0.0:8000

pages:
- Home: 'index.md'
- Navigation:
  - 'General': 'Navigation/general.md'
  - 'Notifications': 'Navigation/notifications.md'
  - 'Proposal Navigation': 'Navigation/proposal.md'
  - 'Summary View Indicators': 'Navigation/indicators.md'
  - 'Preferences': 'Navigation/preferences.md'  
- Data:
  - 'Initiator': 'data/Proposal Initiator.md'
  - 'Proposal Editor': 'data/Proposal Editor.md'
  - 'Budget Development': 'data/Budget Development.md'
  - 'Exporting Data': 'data/Data Exports.md'
- Approvals:
  - 'Proposal Routing': 'Approvals/Proposal Routing.md'
- Toolbar:
  - 'Actions': 'Tools/Actions.md'
  - 'Activity Log': 'Tools/activity.md'
  - 'Comments': 'Tools/Comments.md'
  - 'Files': 'Tools/Files.md'
  - 'History': 'Tools/History.md'
  - 'Requirements': 'Tools/Requirements.md'
- Management:
  - 'Sponsors': 'Management/Sponsor Editor.md'
  - 'Sponsor Vetting': 'Management/Sponsor Vetting.md'
  - 'Organizations': 'Management/Org Editor.md'
  - 'Bulk Operations': 'Management/Bulk Operations.md'
  - 'Assignees': 'Management/Assignees.md'
- Videos: 'videos.md'
- Release Notes: 'releaseNotes.md'
